### ISSUE TITLE
Use a project management tool (GitHub Projects, Trello, etc.) to plan your work

### ISSUE THREAD

**Issue by vacb** [vacb/reddit-client#2]
### Tasks
- [x] Choose a project management tool
- [x] Create a project workflow

### Acceptance criteria
- [x] Project management tool implemented
