### ISSUE TITLE
Write a README (using Markdown) that documents your project

### ISSUE THREAD

**Issue by vacb** [vacb/reddit-client#3]
## Write a README (using Markdown) that documents your project including:
    * Wireframes
    * Technologies used
    * Features
    * Future work
   
### Tasks
- [ ] Create project wireframes
- [ ] Upload project wireframes
- [ ] Update README for technologies used
- [ ] Document all features
- [ ] Decide on future work and document it

### Acceptance criteria
- [ ] README includes information for all specified categories
